# Generated by Django 5.2.4 on 2025-08-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='poster_path',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
