# Generated by Django 5.2.4 on 2025-08-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_favorites_poster_path'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favorites',
            table='accounts_favorites',
        ),
    ]
