# Generated by Django 5.2.4 on 2025-08-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_favorites_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='item_name',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
