# Generated by Django 5.2.4 on 2025-08-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_favorites_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='poster_path',
            new_name='poster_url',
        ),
    ]
